---
title: "Schedule"
---

Please read the specified sections *before* class that day.

::: {#past style="color: lightgray"}

## Week 1

#### Mon, Sep 2

-   No class

#### Tues, Sep 3

-   **Office hours**: No office hours

#### Wed, Sep 4

-   Introduction to the course
-   [Course questionnaire](https://docs.google.com/forms/d/e/1FAIpQLSc23gIulhgDvCQSa0qX7RMxJUcCbVWwvzUxuzJU5G9PraYL_Q/viewform?usp=sf_link)
-   [Short experiment](https://smithcollege.qualtrics.com/jfe/form/SV_71nqdhEpN8frd6B)
-   Homework:
    -   HW #1: CITI training

#### Fri, Sep 6

-   **Office hours**: No office hours
-   Homework due today:
    -   Read **Stat2** Ch. 0 (PDF on Moodle)
    -   Please record your name on Moodle

## Week 2

#### Mon, Sep 9

-   Four-step process
-   One-way ANOVA
-   Homework due today:
    -   Read **Stat2** Ch. 5.1-5.2 (Moodle)
    
#### Tues, Sep 10

-   **Office hours**: 10:30a - 11:30a    

#### Wed, Sep 11

-   One-way ANOVA (cont.)
-   Homework due today:
    -   Read **Stat2** Ch. 5.3

#### Fri, Sep 13

-   **Office hours**: 3:00p - 4:00p
-   Homework due today:
    -   **HW #1 due today at 11:55p**

## Week 3

#### Mon, Sep 16

-   Algebraic notation 
-   Factor diagrams
-   Inference for ANOVA
-   Homework due today:
    -   Read **Stat2** Ch. 5.3 (again!)

#### Tues, Sep 17

-   **Office hours**: 10:30a - 11:30a 
-   Cindy, Nora, Sarah **tutoring Sabin-Reed 301 7-9p**

#### Wed, Sep 18

-   ANOVA Conditions
-   MP1 assignment
-   Homework due today:
    -   Read **Stat2** Ch. 5.4

#### Fri, Sep 20

-   **Office hours**: 3:00p - 4:00p
-   Homework due today:
    -   **HW #2 due today at 11:55p**

## Week 4

#### Mon, Sep 23

-   Transformations
-   Homework due today:
    -   Brainstorm topics for MP1
    -   Read **Stat2** Ch. 5.5-5.6

#### Tues, Sep 24

-   **Office hours**: 10:30a - 11:30a   
-   Cindy, Nora, Sarah **tutoring Sabin-Reed 301 7-9p**

#### Wed, Sep 25

-   Confidence intervals and effect sizes
-   Introduction to Qualtrics
-   Homework due today:
    -   Find potential stimuli (images) for MP1
    -   Read **Stat2** 4.5 (up to, not including, example 4.10)
    -   Read **Stat2** 5.7

#### Fri, Sep 27

-   **Office hours**: 3:00p - 4:00p
-   Homework due today:
    -   **HW #3 due on today at 11:55p**

## Week 5

#### Mon, Sep 30

-   Multiple comparisons
-   Time to work on MP1
-   Homework due today:
    -   Work on Qualtrics survey for MP1

#### Tues, Oct 1

-   Mountain Day!

#### Wed, Oct 2

-   Four basic designs
-   Homework due today:
    -   Read **Cobb** Ch. 1.1-1.3 (PDF on Moodle)

#### Fri, Oct 4

-   **Office hours cancelled**, by appointment only
-   Homework due today:
    -   **HW #4 due on today at 11:55p**


## Week 6

#### Mon, Oct 7

-   Blocking
-   Homework due today:
    -   Read Ch **Stat2** Ch 6.1-6.2

#### Tues, Oct 8

-   **Office hours**: 10:30a - 11:30a  
-   Cindy, Nora, Sarah **tutoring Sabin-Reed 301 7-9p**

#### Wed, Oct 9

-   Fitting the model for a block design
-   Homework due today:
    -   Read Ch **Stat2** Ch 6.3
-   **Office hours**: Thursday 4p-5p and by appointment

#### Fri, Oct 11

-   **Office hours cancelled**
-   Homework due today:
    -   **MP1 Qualtrics survey due for pre-approval by 11:55p**

## Week 7

#### Mon, Oct 14

-   **No Class**: Fall Break

#### Tues, Oct 15

-   **No Office hours**: Fall Break 

#### Thurs, Oct 16

-   MP1 Data Collection Day
-   Complete block design catch-up
-   Homework due today:
    -   Read Ch **Stat2** 6.4-6.5

#### Fri, Oct 18

-   **Office hours**: 3:00p - 4:00p
-   Homework due today:
    -   **HW #5 due tonight at 11:55p**

## Week 8 - Exam 1

#### Mon, Oct 21

-   Review for Exam 1

#### Tues, Oct 22

-   **Office hours**: 10:30a - 11:30a   
-   Cindy, Nora, Sarah **tutoring Sabin-Reed 301 7-9p**

#### Wed, Oct 23

-   **No Class**: Study for Exam 1
-   **Special Exam office hours**: 1:20 - 2:35p

#### Fri, Oct 25

-   **Exam 1 - Self-Scheduled** McConnell Foyer ([more information](https://www.science.smith.edu/self-scheduled-exams/))
    -   Friday 10/25 3-6p
    -   Saturday 10/26 12-6p 
    -   Sunday 10/27 12-6p
-   **Office hours**: 3:00p - 4:00p
-   Homework due today:
    -   No homework

## Week 9 - MP1 due

#### Mon, Oct 28

-   Analysis of MP1 data
-   Complete block design catch-up
-   Homework due today:
    -   Read Ch **Stat2** 6.4-6.5

#### Tues, Oct 29

-   **Office hours**: 10:30a - 11:30a  
-   Cindy, Nora, Sarah **tutoring Sabin-Reed 301 7-9p**

#### Wed, Oct 30

-   Interactions
-   Two-way factorial designs
-   Homework due today:
    -   Read Ch **Stat2** 7.1 - 7.2

#### Fri, Nov 1

-   **Office hours**: 3:00p - 4:00p 
-   Homework due today:
    -   **Mini Project 1 due 11:59p** (upload to Moodle by Midnight)

## Week 10

#### Mon, Nov 4

-   MP2 Assignment and survey
-   Practice designs
-   Fitting two-way ANOVA
-   Homework due today:
    -   Read Ch **Stat2** 7.3, 7.5

#### Tues, Nov 5

-   **Office hours**: 10:30a - 11:30a   
-   Cindy, Nora, Sarah **tutoring Sabin-Reed 301 7-9p**

#### Wed, Nov 6

-   MP1 Self-assessment
-   MP2 group assignments and work time
-   Homework due today:
    -   No reading
    
#### Fri, Nov 8

-   **Office hours**: 3:00p - 4:00p  
-   Homework due today:
    - [**HW #6 due today at 11:55p**](homework.html)  

## Week 11

#### Mon, Nov 11

-   Practice designs
-   Assessing two-way design
-   Homework due today:
    -   No reading

#### Tues, Nov 12

-   **Office hours**: 10:30a - 11:30a   
-   Cindy, Nora, Sarah **tutoring Sabin-Reed 301 7-9p**

#### Wed, Nov 13

-   Multiple tests
-   Inference Test for S Condition
-   Homework due today:
    -   Read Ch **Stat2** 8.1 - 8.2

#### Fri, Nov 15

-   **Office hours**: 3:00p - 4:00p  
-   Homework due today:
    -   [**HW #7 due today at 11:55p**](homework.html)

## Week 12

#### Mon, Nov 18

-   Repeated measures designs 
-   MP2 Work time
-   Homework due today:
    -   Read Ch **Stat2** 8.6

#### Tues, Nov 19

-   **Office hours**: 10:30a - 11:30a   
-   Cindy, Nora, Sarah **tutoring Sabin-Reed 301 7-9p**

#### Wed, Nov 20

-   Repeated measures designs
-   Homework due today:
    -   Read Ch **Stat2** 8.7

#### Fri, Nov 22

-   **Office hours**: 3:00p - 4:00p  
-   Homework due today:
    -   **MP2 Pre-approval due tonight 11:59p** (upload to Moodle)
    -   [**HW #8 due tonight at 11:59p**](homework.html)

## Week 13

#### Mon, Nov 25

-   **No Class**
-   MP2 Data Collection (remotely)

#### Tues, Nov 26

-   **Office hours**: No office hours   

#### Wed, Nov 27

-   No class: Thanksgiving break

#### Fri, Nov 29

-   **Office hours**: No office hours   

## Week 14 - Exam 2

#### Mon, Dec 2

-   Review for Exam 2
-   Homework due today:
    -   [**HW #9 due tonight at 11:59p**](homework.html)

#### Tues, Dec 3

-   **Office hours**: 10:30a - 11:30a   
-   Cindy, Nora, Sarah **tutoring Sabin-Reed 301 7-9p**

#### Wed, Dec 4

-   **Exam 2** (Option to take in-class during class time)

#### Fri, Dec 6

-   **Office hours**: 3:00p - 4:00p  
-   **Exam 2 - Self-Scheduled** McConnell Foyer ([more information](https://www.science.smith.edu/self-scheduled-exams/))
    -   Friday 12/6 3-6p
    -   Saturday 12/7 12-6p 
    -   Sunday 12/8 12-6p
-   Homework due today:
    -   No homework

::: 

## Week 15 

#### Mon, Dec 9

-   MP2 Data Analysis and group work time
-   Class wrap-up

#### Tues, Dec 10

-   **Office hours**: 10:30a - 11:30a   
-   Cindy, Nora, Sarah **tutoring Sabin-Reed 301 7-9p**

#### Wed, Dec 11

-   No class

#### Fri, Dec 13

-   **Office hours**: No office hours
    

## Finals Week - MP2 due

#### Mon, Dec 16

-   No class

#### Tues, Dec 17

-   **Office hours**: No office hours, by appointment   

#### Wed, Dec 18

-   **MP2 due today at formal end of finals. Typically 2p or 3p.** (upload to Moodle)
-   **MP2 Peer Evaluation due today at formal end of finals. Typically 2p or 3p.** (upload to Moodle)

