---
title: "MP2 Analysis"
author: Prof Randi Garcia, SDS 290
date: December 9, 2024
format: 
  revealjs:
    scrollable: true
    theme: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE, echo = TRUE)
library(tidyverse)
library(Stat2Data)
```

## Announcements

-   MP1 Grades and feedback
-   MP2 Peer Evaluation
-   Course evaluation today
-   Office hours (Bass 412)
    -   Tuesday 10:30a - 11:30a 
    -   By appointment next week

## MP2 Feedback

- Overall Writing 
    - Improve scientific tone by reducing narrative
    - Grammar issues
    - Finding the right level of hedging in your language
- Introduction section
    - Be sure you introduction gives brief reference to your factors and their levels enough for me to understand your hypotheses. Hypotheses should cover all levels of your factors. 
- Method section
    - Be sure to mention random assignment. 
    - Include images or vingettes, if relevant. 
    - Be specific about your response variable questions.
    - Most everyone needed more description in their their method section. A person brand new to your study should be able to replicate it. 
- Results and Statistical writing
    - Integrating statistical information into your text, (two to three decimal places only, p < .001 please). Your statistical information should be used to tell a coherent, accurate, story/description of your results. Move away from listing results. 
    - Do not include information about data cleaning. Do not tell me anything about your downloading the data. 
- Your conclusion should actually discuss your results, especially if they are counter to your hypotheses. No, your results are not "obvious."

# Course evaluation time

# MP2 Group Work time
